package OOP;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Admin
 */
public class GDNhanVienXuat extends javax.swing.JFrame {

    /**
     * Creates new form ADMIN
     *
     * @param ten
     */
    public GDNhanVienXuat(String ten) {
        initComponents();
        ShowCBE();
        load();
        jLabel18.setText(ten);
    }
    ArrayList<Account> list = new ArrayList<>();

    public GDNhanVienXuat() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel24 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton15 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel16 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel17 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jButton22 = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();

        jLabel24.setBackground(new java.awt.Color(7, 138, 68));
        jLabel24.setText("jLabel24");
        jLabel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel24.setOpaque(true);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 150));
        setMinimumSize(new java.awt.Dimension(970, 550));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setMaximumSize(new java.awt.Dimension(970, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(970, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(970, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(7, 138, 68));
        jPanel2.setMaximumSize(new java.awt.Dimension(160, 530));
        jPanel2.setMinimumSize(new java.awt.Dimension(160, 530));
        jPanel2.setPreferredSize(new java.awt.Dimension(160, 530));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setBackground(new java.awt.Color(7, 138, 68));
        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Thông tin tài khoản");
        jLabel46.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel46.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel46.setOpaque(true);
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 32));

        jLabel15.setBackground(new java.awt.Color(7, 138, 68));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("D/s phiếu xuất");
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.setOpaque(true);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 160, 32));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("jLabel18");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 100, 32));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("   Hello,");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 32));

        jLabel22.setBackground(new java.awt.Color(7, 138, 68));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Xuất hàng");
        jLabel22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.setOpaque(true);
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 160, 32));

        jLabel26.setBackground(new java.awt.Color(7, 138, 68));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("D/s sản phẩm");
        jLabel26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel26.setOpaque(true);
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 160, 32));

        jLabel28.setBackground(new java.awt.Color(7, 138, 68));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Đăng xuất");
        jLabel28.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.setOpaque(true);
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 160, 32));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_phonelink_setup_24px_1.png"))); // NOI18N
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 970, 10));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setMaximumSize(new java.awt.Dimension(810, 32));
        jPanel3.setMinimumSize(new java.awt.Dimension(810, 32));
        jPanel3.setPreferredSize(new java.awt.Dimension(810, 32));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(7, 138, 68));
        jLabel9.setText("-");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(7, 138, 68));
        jLabel4.setText("X");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(916, 916, 916)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 970, 30));

        jPanel4.setMaximumSize(new java.awt.Dimension(810, 500));
        jPanel4.setMinimumSize(new java.awt.Dimension(810, 500));

        jPanel6.setForeground(new java.awt.Color(7, 138, 68));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.setMaximumSize(new java.awt.Dimension(810, 500));
        jPanel6.setMinimumSize(new java.awt.Dimension(810, 500));
        jPanel6.setPreferredSize(new java.awt.Dimension(810, 500));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(7, 138, 68));
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField9KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField9KeyReleased(evt);
            }
        });
        jPanel6.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 690, 32));

        jTable3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable3.setForeground(new java.awt.Color(7, 138, 68));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jTable3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable3ComponentShown(evt);
            }
        });
        jScrollPane4.setViewportView(jTable3);

        jPanel6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 70, 730, 410));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_package_search_32px.png"))); // NOI18N
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jPanel8.setMaximumSize(new java.awt.Dimension(810, 500));
        jPanel8.setMinimumSize(new java.awt.Dimension(810, 500));
        jPanel8.setPreferredSize(new java.awt.Dimension(810, 500));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(7, 138, 68));
        jLabel20.setText("Số lượng");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 69, 32));

        jTable4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable4.setForeground(new java.awt.Color(7, 138, 68));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID sản phẩm", "Tên sản phẩm", "Số lượng", "Giá", "Thành tiền"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable4);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 750, 250));

        jButton11.setBackground(new java.awt.Color(7, 138, 68));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Sửa");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 60, 32));

        jButton12.setBackground(new java.awt.Color(7, 138, 68));
        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Xóa");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 60, 32));

        jButton13.setBackground(new java.awt.Color(7, 138, 68));
        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Thêm");
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 70, 32));

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(7, 138, 68));
        jPanel8.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 230, 32));

        jButton15.setBackground(new java.awt.Color(7, 138, 68));
        jButton15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Xuất Hàng");
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 110, 32));

        jTextField11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(7, 138, 68));
        jPanel8.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 230, 32));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(7, 138, 68));
        jLabel21.setText("Tên sản phẩm");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 32));

        jTable7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable7.setForeground(new java.awt.Color(7, 138, 68));
        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date Import", "Staff"
            }
        ));
        jTable7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable7MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTable7);

        jTable8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable8.setForeground(new java.awt.Color(7, 138, 68));
        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProID", "ProName", "Quantity", "Total"
            }
        ));
        jScrollPane8.setViewportView(jTable8);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.setForeground(new java.awt.Color(7, 138, 68));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(7, 138, 68));
        jLabel36.setText("jLabel36");
        jLabel36.setPreferredSize(new java.awt.Dimension(180, 32));

        jTextField20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField20.setForeground(new java.awt.Color(7, 138, 68));
        jTextField20.setMaximumSize(new java.awt.Dimension(180, 32));
        jTextField20.setMinimumSize(new java.awt.Dimension(180, 32));
        jTextField20.setPreferredSize(new java.awt.Dimension(180, 32));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(7, 138, 68));
        jLabel37.setText("Tài khản");
        jLabel37.setMaximumSize(new java.awt.Dimension(180, 32));
        jLabel37.setMinimumSize(new java.awt.Dimension(180, 32));
        jLabel37.setPreferredSize(new java.awt.Dimension(180, 32));

        jTextField22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField22.setForeground(new java.awt.Color(7, 138, 68));
        jTextField22.setMaximumSize(new java.awt.Dimension(180, 32));
        jTextField22.setMinimumSize(new java.awt.Dimension(180, 32));
        jTextField22.setPreferredSize(new java.awt.Dimension(180, 32));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(7, 138, 68));
        jLabel39.setText("Mật khẩu hiện tại");

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(7, 138, 68));
        jLabel40.setText("Mật khẩu mới");

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(7, 138, 68));
        jLabel41.setText("Xác nhận mật khẩu");

        jButton20.setBackground(new java.awt.Color(7, 138, 68));
        jButton20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("Xác nhận");
        jButton20.setMaximumSize(new java.awt.Dimension(100, 32));
        jButton20.setMinimumSize(new java.awt.Dimension(100, 32));
        jButton20.setPreferredSize(new java.awt.Dimension(100, 32));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordField1)))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Đổi mật khẩu", jPanel16);

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(7, 138, 68));
        jLabel42.setText("Họ và tên");
        jLabel42.setMaximumSize(new java.awt.Dimension(100, 32));
        jLabel42.setMinimumSize(new java.awt.Dimension(100, 32));
        jLabel42.setPreferredSize(new java.awt.Dimension(100, 32));
        jPanel17.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 74, -1, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(7, 138, 68));
        jLabel43.setText("Ngày sinh");
        jLabel43.setMaximumSize(new java.awt.Dimension(100, 32));
        jLabel43.setMinimumSize(new java.awt.Dimension(100, 32));
        jLabel43.setPreferredSize(new java.awt.Dimension(100, 32));
        jPanel17.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 141, -1, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(7, 138, 68));
        jLabel44.setText("Địa chỉ");
        jLabel44.setMaximumSize(new java.awt.Dimension(100, 32));
        jLabel44.setMinimumSize(new java.awt.Dimension(100, 32));
        jLabel44.setPreferredSize(new java.awt.Dimension(100, 32));
        jPanel17.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 208, -1, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(7, 138, 68));
        jLabel45.setText("Số điện thoại");
        jLabel45.setMaximumSize(new java.awt.Dimension(100, 32));
        jLabel45.setMinimumSize(new java.awt.Dimension(100, 32));
        jLabel45.setPreferredSize(new java.awt.Dimension(100, 32));
        jPanel17.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 275, -1, -1));

        jTextField23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField23.setForeground(new java.awt.Color(7, 138, 68));
        jTextField23.setMaximumSize(new java.awt.Dimension(200, 32));
        jTextField23.setMinimumSize(new java.awt.Dimension(200, 32));
        jTextField23.setPreferredSize(new java.awt.Dimension(200, 32));
        jPanel17.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 74, -1, -1));

        jTextField24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField24.setForeground(new java.awt.Color(7, 138, 68));
        jTextField24.setMaximumSize(new java.awt.Dimension(200, 32));
        jTextField24.setMinimumSize(new java.awt.Dimension(200, 32));
        jTextField24.setPreferredSize(new java.awt.Dimension(200, 32));
        jPanel17.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 141, -1, -1));

        jTextField25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField25.setForeground(new java.awt.Color(7, 138, 68));
        jTextField25.setMaximumSize(new java.awt.Dimension(200, 32));
        jTextField25.setMinimumSize(new java.awt.Dimension(200, 32));
        jTextField25.setPreferredSize(new java.awt.Dimension(200, 32));
        jPanel17.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 208, -1, -1));

        jTextField26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField26.setForeground(new java.awt.Color(7, 138, 68));
        jTextField26.setMaximumSize(new java.awt.Dimension(200, 32));
        jTextField26.setMinimumSize(new java.awt.Dimension(200, 32));
        jTextField26.setPreferredSize(new java.awt.Dimension(200, 32));
        jPanel17.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 275, -1, -1));

        jButton22.setBackground(new java.awt.Color(7, 138, 68));
        jButton22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("Xác nhận");
        jButton22.setMaximumSize(new java.awt.Dimension(100, 32));
        jButton22.setMinimumSize(new java.awt.Dimension(100, 32));
        jButton22.setPreferredSize(new java.awt.Dimension(100, 32));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(7, 138, 68));
        jLabel56.setText("ID");
        jPanel17.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 55, 32));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(7, 138, 68));
        jLabel57.setText("jLabel49");
        jPanel17.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 200, 32));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(7, 138, 68));
        jLabel59.setText("jLabel51");
        jPanel17.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 330, 200, 32));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(7, 138, 68));
        jLabel58.setText("Chức vụ");
        jPanel17.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, 32));

        jTabbedPane1.addTab("Thông tiên cá nhân", jPanel17);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 810, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát ứng dụng?", "Thoát", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel4MouseClicked
    int X, Y;
    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        setLocation(evt.getXOnScreen() - X, evt.getYOnScreen() - Y);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        X = evt.getX();
        Y = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        LoadDataP();
        LoadDataLE();
        LoadDataT();

    }//GEN-LAST:event_formComponentShown
    ArrayList<Products> list1 = new ArrayList<>();

    public void LoadDataP() {
        Connection con = DBConnect.getJDBCConnection();
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM product;");
            list1.clear();
            while (rs.next()) {
                String id = rs.getString(1);
                String name = rs.getString(2);
                String sl = rs.getString(3);
                String gia = rs.getString(4);
                String ncc = rs.getString(5);
                Products pr = new Products(name, ncc, id, sl, gia);
                list1.add(pr);
            }
            con.close();
            DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
            model.setRowCount(0);
            for (Products o : list1) {
                model.addRow(new Object[]{o.getIdsp(), o.getTensp(), o.getSlsp(), o.getGiasp(), o.getNccsp()});
            }
            model.setColumnIdentifiers(new Object[]{
                "ID sản phẩm", "Tên", "Số lượng", "Giá", "NCC"});
        } catch (SQLException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void SearchP() {
        Connection con = DBConnect.getJDBCConnection();
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM product where id like N'%" + jTextField9.getText() + "%' "
                    + "or proname like  N'%" + jTextField9.getText() + "%' or sl like N'%" + jTextField9.getText()
                    + "%' or gia like N'%" + jTextField9.getText() + "%' or ncc like N'%" + jTextField9.getText() + "%';");
            list1.clear();
            while (rs.next()) {
                String id = rs.getString(1);
                String name = rs.getString(2);
                String sl = rs.getString(3);
                String gia = rs.getString(4);
                String ncc = rs.getString(5);
                Products pr = new Products(name, ncc, id, sl, gia);
                list1.add(pr);
            }
            con.close();
            DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
            model.setRowCount(0);
            for (Products o : list1) {
                model.addRow(new Object[]{o.getIdsp(), o.getTensp(), o.getSlsp(), o.getGiasp(), o.getNccsp()});
            }
            model.setColumnIdentifiers(new Object[]{
                "ID sản phẩm", "Tên", "Số lượng", "Giá", "NCC"});
        } catch (SQLException ex) {
            Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void jTextField9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyPressed

    }//GEN-LAST:event_jTextField9KeyPressed

    private void jTextField9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyReleased
        // TODO add your handling code here:
        if (jTextField9.getText().equals("")) {
            LoadDataP();
        } else {
            SearchP();
        }
    }//GEN-LAST:event_jTextField9KeyReleased
    void load() {
        jLabel26.setBackground(new Color(7, 204, 68));
        try {
            jPanel4.removeAll();
            jPanel4.repaint();
            jPanel4.revalidate();
            //adding a pannel 
            jPanel4.add(jPanel6);
            jPanel4.repaint();
            jPanel4.revalidate();
        } catch (Exception e) {

        }
    }
    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable3ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3ComponentShown

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        LoadDataLE();
        jLabel15.setBackground(new Color(7, 204, 68));
        jLabel26.setBackground(new Color(7, 138, 68));
        jLabel22.setBackground(new Color(7, 138, 68));
        jLabel46.setBackground(new Color(7, 138, 68));
        try {
            //clearing
            jPanel4.removeAll();
            jPanel4.repaint();
            jPanel4.revalidate();
            //adding a pannel 
            jPanel4.add(jPanel10);
            jPanel4.repaint();
            jPanel4.revalidate();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        int index = jTable4.getSelectedRow();
        TableModel model = jTable4.getModel();
        jTextField11.setText(model.getValueAt(index, 2).toString());
        jComboBox2.setSelectedItem(model.getValueAt(index, 1).toString());
    }//GEN-LAST:event_jTable4MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        for (Add h : list6) {
            if (h.getTen() == jComboBox2.getSelectedItem()) {
                h.sl = jTextField11.getText();
            }
        }
        LoadDataE();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        int index = jTable4.getSelectedRow();
        list6.remove(index);
        LoadDataE();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        model.setRowCount(0);
        for (Products o : list7) {
            mo:
            {
                if (o.getTensp() == jComboBox2.getSelectedItem()) {
                    for (Add h : list6) {
                        if (h.getTen() == jComboBox2.getSelectedItem()) {
                            h.sl = String.valueOf(Integer.parseInt(jTextField11.getText()) + Integer.parseInt(h.sl));
                            break mo;
                        }
                    }
                    int d = Integer.parseInt(jTextField11.getText()) * Integer.parseInt(o.getGiasp());
                    Add a = new Add(o.getIdsp(), o.getTensp(), jTextField11.getText(), o.getGiasp(), String.valueOf(d));
                    list6.add(a);
                }
            }
        }
        LoadDataE();
    }//GEN-LAST:event_jButton13ActionPerformed
    ArrayList<Add> list6 = new ArrayList<>();
    ArrayList<Products> list7 = new ArrayList<>();

    public void ShowCBE() {
        Connection con = DBConnect.getJDBCConnection();
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM product;");
            list7.clear();
            while (rs.next()) {
                String idp = rs.getString(1);
                String name = rs.getString(2);
                String slp = rs.getString(3);
                String giap = rs.getString(4);
                String ncc = rs.getString(5);
                Products pr = new Products(name, ncc, idp, slp, giap);
                list7.add(pr);
            }
            for (Products o : list7) {
                jComboBox2.addItem(o.tensp);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Thông tin chưa chính xác!!!");
        }
    }

    public void LoadDataE() {
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        model.setRowCount(0);
        for (Add o : list6) {
            model.addRow(new Object[]{o.getId(), o.getTen(), o.getSl(), o.getGia(), o.getThanhtien()});
        }
        model.setColumnIdentifiers(new Object[]{
            "ID sản phẩm", "Tên sản phẩm", "Số lượng", "Giá", "Thành tiền"});
    }

    private void tao2(int n) {
        Connection con = DBConnect.getJDBCConnection();
        try {
            DateNow k = new DateNow();
            PreparedStatement st = con.prepareStatement("INSERT INTO export VALUES (?,?,?);");
            st.setInt(1, n);
            st.setString(2, k.sdf.format(k.date));
            st.setString(3, jLabel18.getText());
            st.executeUpdate();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Y!!!");
        }
    }

    private void tao3(int n) {
        Connection con = DBConnect.getJDBCConnection();
        try {
            PreparedStatement st = con.prepareStatement("INSERT INTO xuathang VALUES (?,?,?,?,?);");
            for (Add list8 : list6) {
                st.setInt(1, n);
                st.setInt(2, Integer.parseInt(list8.getId()));
                st.setString(3, list8.getTen());
                st.setInt(4, Integer.parseInt(list8.getSl()));
                st.setInt(5, Integer.parseInt(list8.getThanhtien()));
                st.executeUpdate();
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "X!!");
        }
    }

    public int layid1() {
        int d = 0;
        Connection con = DBConnect.getJDBCConnection();
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM export;");
            while (rs.next()) {
                d++;
            }
            return d + 1;
        } catch (SQLException ex) {
            Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Thông tin chưa chính xác!!!");
            return 0;
        }
    }
    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn xuất hàng?", "Xuất hàng", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            int r = list6.size();
            for (Add s : list6) {
                for (Products f : list1) {
                    if (s.getId().equals(f.getIdsp())) {
                        if (Integer.parseInt(f.getSlsp()) - Integer.parseInt(s.getSl()) >= 0) {
                            r--;
                        }
                    }
                }
            }
            if (r == 0) {
                int n = layid1();
                Connection con = DBConnect.getJDBCConnection();
                tao2(n);
                tao3(n);
                try {
                    PreparedStatement st = con.prepareStatement("UPDATE product SET sl=sl - ? WHERE id=?;");
                    for (Add list8 : list6) {
                        st.setInt(1, Integer.parseInt(list8.getSl()));
                        st.setInt(2, Integer.parseInt(list8.getId()));
                        st.executeUpdate();
                    }
                    JOptionPane.showMessageDialog(this, "Đã xuất hàng thành công!");
                    con.close();
                    list6.clear();
                    LoadDataE();
                } catch (SQLException ex) {
                    Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Thông tin chưa chính xác!!!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Không đủ số lượng để xuất");
            }
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        jLabel15.setBackground(new Color(7, 138, 68));
        jLabel26.setBackground(new Color(7, 138, 68));
        jLabel22.setBackground(new Color(7, 204, 68));
        jLabel46.setBackground(new Color(7, 138, 68));
        try {
            //clearing
            jPanel4.removeAll();
            jPanel4.repaint();
            jPanel4.revalidate();
            //adding a pannel 
            jPanel4.add(jPanel8);
            jPanel4.repaint();
            jPanel4.revalidate();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
        LoadDataP();
        jLabel15.setBackground(new Color(7, 138, 68));
        jLabel26.setBackground(new Color(7, 204, 68));
        jLabel22.setBackground(new Color(7, 138, 68));
        jLabel46.setBackground(new Color(7, 138, 68));
        try {
            //clearing
            jPanel4.removeAll();
            jPanel4.repaint();
            jPanel4.revalidate();
            //adding a pannel 
            jPanel4.add(jPanel6);
            jPanel4.repaint();
            jPanel4.revalidate();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn đăng xuất?", "Đăng xuất", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new DangNhap().setVisible(true);
        }
    }//GEN-LAST:event_jLabel28MouseClicked
    ArrayList<ListN> list11 = new ArrayList<>();
    ArrayList<Add> list12 = new ArrayList<>();

    public void LoadDataLE() {
        Connection con = DBConnect.getJDBCConnection();
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM export;");
            list11.clear();
            while (rs.next()) {
                String ngay, ten;
                int id = rs.getInt(1);
                ngay = rs.getString(2);
                ten = rs.getString(3);
                ListN v = new ListN(id, ngay, ten);
                list11.add(v);
            }
            con.close();
            DefaultTableModel model = (DefaultTableModel) jTable7.getModel();
            model.setRowCount(0);
            for (ListN o : list11) {
                model.addRow(new Object[]{o.getId(), o.getNgaynhap(), o.getNguoinhap()});
            }
            model.setColumnIdentifiers(new Object[]{
                "ID", "Ngày nhập", "Người nhập"});
        } catch (SQLException ex) {
            Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void LoadDataLE1(String a) {
        Connection con = DBConnect.getJDBCConnection();
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM oop.xuathang WHERE id= " + a + ";");
            list12.clear();
            while (rs.next()) {
                String id, ten, sl, gia, thanhtien;
                id = rs.getString(2);
                ten = rs.getString(3);
                sl = rs.getString(4);
                thanhtien = rs.getString(5);
                Add v = new Add(id, ten, sl, null, thanhtien);
                list12.add(v);
            }
            con.close();
            DefaultTableModel model = (DefaultTableModel) jTable8.getModel();
            model.setRowCount(0);
            for (Add o : list12) {
                model.addRow(new Object[]{o.getId(), o.getTen(), o.getSl(), o.getThanhtien()});
            }
            model.setColumnIdentifiers(new Object[]{
                "ID sản phẩm", "Tên sản phẩm", "Số lượng", "Thành tiền"});
        } catch (SQLException ex) {
            Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jTable7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable7MouseClicked
        // TODO add your handling code here:
        int index = jTable7.getSelectedRow();
        TableModel model = jTable7.getModel();
        LoadDataLE1(model.getValueAt(index, 0).toString());
    }//GEN-LAST:event_jTable7MouseClicked

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
        // TODO add your handling code here:
        jLabel15.setBackground(new Color(7, 138, 68));
        jLabel26.setBackground(new Color(7, 138, 68));
        jLabel22.setBackground(new Color(7, 138, 68));
        jLabel46.setBackground(new Color(7, 204, 68));
        try {
            //clearing
            jPanel4.removeAll();
            jPanel4.repaint();
            jPanel4.revalidate();
            //adding a pannel 
            jPanel4.add(jPanel15);
            jPanel4.repaint();
            jPanel4.revalidate();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jLabel46MouseClicked

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Bạn có đổi mật khẩu?", "Đổi mật khẩu", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            Connection con = DBConnect.getJDBCConnection();
            PreparedStatement ps, ps1;
            try {
                ps = con.prepareStatement("SELECT * FROM oop.account WHERE usename=? AND password=?");
                ps.setString(1, jLabel36.getText());
                ps.setString(2, jPasswordField1.getText());
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    ps1 = con.prepareStatement("select * from oop.account,oop.nhanvien where oop.account.idnv=oop.nhanvien.idnv and usename=?");
                    ps1.setString(1, jLabel36.getText());
                    ResultSet rs1 = ps1.executeQuery();
                    rs1.next();
                    if (!jTextField20.getText().equals(jTextField22.getText())) {
                        JOptionPane.showMessageDialog(this, "Mật khẩu xác nhận không đúng!?!");
                        return;
                    }
                    PreparedStatement st = con.prepareStatement("UPDATE account SET password=? WHERE usename=?;");
                    st.setString(2, jLabel36.getText());
                    st.setString(1, jTextField20.getText());
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Thành Công!!");
                    con.close();
                } else {
                    JOptionPane.showMessageDialog(null, "Mật khẩu không đúng", null, JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn đổi thông tin?", "Đổi thông tin cá nhân", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            Connection con = DBConnect.getJDBCConnection();
            try {
                PreparedStatement st = con.prepareStatement("UPDATE nhanvien SET hoten=?,ngaysinh=?,diachi=?,sdt=?,chucvu=? WHERE idnv=?;");
                st.setInt(6, Integer.parseInt(jLabel57.getText()));
                st.setString(1, jTextField23.getText());
                st.setString(2, jTextField24.getText());
                st.setString(3, jTextField25.getText());
                st.setString(4, jTextField26.getText());
                st.setString(5, jLabel59.getText());
                st.executeUpdate();
                JOptionPane.showMessageDialog(this, "Sửa thành công!");
                con.close();
                LoadDataT();
            } catch (SQLException ex) {
                Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Thông tin chưa chính xác!!!");
            }
        }
    }//GEN-LAST:event_jButton22ActionPerformed
    public void LoadDataT() {
        Connection con = DBConnect.getJDBCConnection();
        try {
            PreparedStatement ps = con.prepareStatement("select * from oop.account,oop.nhanvien where oop.account.idnv=oop.nhanvien.idnv and hoten=?");
            ps.setString(1, jLabel18.getText());
            ResultSet rs = ps.executeQuery();
            rs.next();
            jLabel57.setText(rs.getString("idnv"));
            jLabel36.setText(rs.getString("usename"));
            jTextField23.setText(rs.getString("hoten"));
            jTextField24.setText(rs.getString("ngaysinh"));
            jTextField25.setText(rs.getString("diachi"));
            jTextField26.setText(rs.getString("sdt"));
            jLabel59.setText(rs.getString("chucvu"));
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GDNhanVienXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GDNhanVienXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GDNhanVienXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GDNhanVienXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GDNhanVienXuat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton22;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
